Add Vue support
pzavolinsky/ts-unused-exports pull request #171
Opened 2020-10-20 13:24 UTC by Timmmm

This also adds a test that may or may not test anything.

Fixes #162

2020-10-20 17:43 UTC, mrseanryan requested changes
Nice work - a few TODOs:

________________________________________
A) README

TODO - add note to README on Vue support. Something like this:

_____________________

VUE Support

1. To process VUE files, your tsconfig.json should include the vue files:

```
"include": ["./**/*.ts", "./**/*.vue"],
```

2. Suppress warnings about the `shims-vue.d.ts` file (default export from Vue components).   To do this, use the `ignoreFiles` option:

```
--ignoreFiles=shims-vue.d.ts
```

________________________________________
B) CHANGELOG

Please add an 'Added' entry to the top of the CHANGELOG.md file

2020-10-20 17:43 UTC, mrseanryan commented on example/vue/tsconfig.json
> +  "atom": {
Remove `atom` section

2020-10-20 17:43 UTC, mrseanryan commented on src/app.ts
> +          scriptKind: ts.ScriptKind.Deferred,
I wonder could this cause any issues.

For example if an existing user has some `vue` files that they do NOT want scanned.

Maybe this part should be behind a new option like `--vue` - then that could also auto-suppress the shims file `shims-tsx-d-ts`

2020-10-20 17:44 UTC, mrseanryan commented on src/app.ts
> +          scriptKind: ts.ScriptKind.Deferred,
Then, the README change is much smaller  (just document the new option)

2020-10-20 17:44 UTC, mrseanryan commented on src/app.ts
> +          scriptKind: ts.ScriptKind.Deferred,
I prefer the approach of adding a new option `--vue` 

@pzavolinsky what do you reckon ?

2020-10-20 18:09 UTC, mrseanryan commented
(related) TODO @mrseanryan check what happens if more than 3 issues found -> itest should fail ...

2020-10-21 01:22 UTC, mrseanryan requested changes

2020-10-21 01:22 UTC, mrseanryan commented on example/vue/math.ts
> +export function add1(x: number) { return x + 1; }
Rename add1 to unused

2020-10-21 01:22 UTC, mrseanryan commented on example/vue/math.ts
> +export function add2(x: number) { return x + 2; }
Rename add2 to unusedButDisabled

2020-10-21 01:23 UTC, mrseanryan commented
TODO add itest with more complex embedded Typescript.

TODO @Timmmm what about Mixins? Looks like something that could require special support.

Ref = https://blog.logrocket.com/how-to-write-a-vue-js-app-completely-in-typescript/

Are there any other Vue features we need to think about?

2020-10-21 01:25 UTC, mrseanryan commented on src/app.ts
> +          scriptKind: ts.ScriptKind.Deferred,
Please add comme t to explain the values used for:

isMixedContent,
          scriptKind

2020-10-21 01:27 UTC, mrseanryan requested changes
Comments needed to explain parameters chosen.

Concern about advanced Vue features like Mixins

2020-10-21 01:45 UTC, mrseanryan commented
TODO add a new **unit test** file

The PR has an itest, but some unit tests are needed for future maintenance and debugging. 

Add a new file like: vue.feature

Example:

https://github.com/pzavolinsky/ts-unused-exports/blob/master/features/base-url-undefined.feature

2020-10-21 10:00 UTC, Timmmm commented on example/vue/tsconfig.json
> +  "atom": {
Hmm yeah not sure why this is in here - I just copied it from another example, you might want to delete it there too.

2020-10-21 10:02 UTC, Timmmm commented on example/vue/math.ts
> +export function add1(x: number) { return x + 1; }
These functions were just copied from another example, I left the names for consistency.

2020-10-21 10:05 UTC, Timmmm commented
> what about Mixins? Looks like something that could require special support.

I think mixins are [a standard Typescript feature](https://www.typescriptlang.org/docs/handbook/mixins.html).

2020-10-21 20:10 UTC, mrseanryan commented
@Timmmm about the itest not failing:

The itests use the `exitWithCount` option:

> Set the process exit code to be the count of files that have unused exports.     

So it is not counting the number of unused items - it is counting the *files*.

When I tried it on this branch, it worked ok (by making a copy of Math.ts)

2020-10-21 20:16 UTC, mrseanryan commented on example/vue/tsconfig.json
> +  "atom": {
Probably, but we can start by removing it here ...

2020-10-21 20:32 UTC, mrseanryan commented on example/vue/tsconfig.json
> +  "atom": {
Logged #172 but if we can some of it here that would be no harm, as adding new files.

2020-10-25 15:25 UTC, mrseanryan commented on example/vue/tsconfig.json
> +  "atom": {
#172 has been fixed

2020-10-25 15:25 UTC, mrseanryan commented on example/vue/math.ts
> +export function add1(x: number) { return x + 1; }
Fixed in master - if you rebase you will see.

2024-08-08 21:07 UTC, closed without merging

2024-08-10 09:28 UTC, FlorianWendelborn commented
Since this is closed now, in case someone is still looking for a Vue compatible alternative you may want to try `knip`