fix: file name containing 'index.' is not ignored by ignoreFile regex…
pzavolinsky/ts-unused-exports pull request #223
Opened 2022-09-02 08:18 UTC by wongjiahau

Fixes #222

2022-09-10 12:22 UTC, mrseanryan commented
@pzavolinsky  PR to process.

Travis is still blocking - could we just turn it off?

2022-09-10 12:26 UTC, mrseanryan requested changes

2022-09-10 12:26 UTC, mrseanryan commented on ispec/_run-and-check-exit-code-zero.sh
>      node ../../bin/ts-unused-exports tsconfig.json --exitWithUnusedTypesCount --excludePathsFromReport=to-ignore $1
This will drop the hard coded args:

line 18:
```
--showLineNumber
```

line 19:
```
--silent
```


Maybe $1 $2 could work.

2022-09-12 18:28 UTC, pzavolinsky commented
@wongjiahau I just merged one @mrseanryan that flew under my radar changing the release process to GH Actions, sorry to use you as guinea pig, but could you rebase your PR to see if we get the proper CI build working?

2022-12-03 19:47 UTC, merged

2022-12-03 19:48 UTC, mrseanryan commented
hi @wongjiahau  many thanks for this fix.

Finally I managed to fix the CI build for PRs,
so we got it merged :)

Sean