feat: get all files by their exports are unused
pzavolinsky/ts-unused-exports pull request #254
Opened 2022-12-11 08:32 UTC by brandonxiang

#253

2022-12-11 19:04 UTC, mrseanryan commented
Thank you for the PR.

Can you please add an itest to cover.

This involves adding another example under ./example
and then adding a call in:

ispec/run.sh

---

Also, please add an entry at top of CHANGELOG.md

2022-12-11 19:11 UTC, mrseanryan commented
Also to `show the output` - need to extend `cli.ts`

Unless the `silent` option is on, then we should display the "completely unused files".

Those can be show, after the existing messages.

2022-12-11 19:15 UTC, mrseanryan commented
TODO - fix so the itests pass

(should not need to change the itests)

Probably this can be fixed by updating `cli.ts`

2022-12-11 19:17 UTC, mrseanryan requested changes
see comments, thank you

2022-12-11 19:17 UTC, mrseanryan commented on src/analyzer.ts
> +  for (let i = 0; i < a.length; i++) {
With `forEach()` could be shorter:

a.forEach(aItem =>

2022-12-12 15:18 UTC, brandonxiang commented
OK, I will spend some time to refactor that code.

2022-12-12 16:12 UTC, mrseanryan commented
good, I will look again when you push

2022-12-18 09:30 UTC, brandonxiang commented
<img width="498" alt="image" src="https://user-images.githubusercontent.com/12969424/208290527-65fa76a0-4b82-448c-8959-70c652ea4c42.png">
I have a confused whether I should put the completelyUnused attribute inside the Analysis Object. 

Whether I should use the original analysis function?

2022-12-18 13:18 UTC, mrseanryan commented
> I have a confused whether I should put the completelyUnused attribute inside the Analysis Object.
Whether I should use the original analysis function?

Let's add it to the Analysis type, as optional. Like:

```
export interface Analysis {
  [index: string]: ExportNameAndLocation[];
  unusedFiles?: string[]; // <<<<<<
}
```

Then, we can still just export 1 function, as before:

```
export default (
  files: File[],
  extraOptions?: ExtraCommandLineOptions,
): Analysis => {
 // (existing code)
 // ...

 if (extraOptions.findCompletelyUnusedFiles) // <<<
   analysis.unusedFiles = getUnusedFiles(files, extraOptions);  // <<<

return analysis;
}
```

This extends the API rather than changes it, which is less risky and is easier for users to pick up...

2022-12-18 13:20 UTC, mrseanryan commented
TODO:

* [ ] add an option `findCompletelyUnusedFiles` and doc it in the README

2022-12-19 16:51 UTC, brandonxiang commented
1. I have put the unusedFiles logic into the analysis function. All calculation is only only.
2. I have written the itest by cucumber-js and finished the doc

2022-12-26 16:08 UTC, mrseanryan commented
* [ ] add CHANGELOG entry

2022-12-26 17:40 UTC, mrseanryan commented
hi brandonxiang

There were a couple of things I wanted to tidy up (and also avoid adding lodash)
so I just made a new PR.

It is merged!

Will release shortly, as new Major version.

Thank you for contributing !

2022-12-26 17:40 UTC, closed without merging